### ISSUE TITLE
Peer Review:Issue:CSS duplication

### ISSUE THREAD

**Issue by RileyManda** [DevaWinner/Leader-board#2]
There are multiple selectors that have the same property values assigned to colors in your CSS.
<img width="100" alt="Screen Shot 2023-06-30 at 9 43 29 AM" src="https://github.com/DevaWinner/Leader-board/assets/37291194/3fc5ca74-3f58-4bca-92fe-a6bdcda2ad1f">
Please use root  pseudo-elements for your colors to resolve this:
```
:root {
  --primary-color: #FF0000;
}

.selector1 {
  color: var(--primary-color);
}

.selector2 {
  color: var(--primary-color);
}
```

**Comment by DevaWinner** [comment]
> There are multiple selectors that have the same property values assigned to colors in your CSS. <img alt="Screen Shot 2023-06-30 at 9 43 29 AM" width="100" src="https://user-images.githubusercontent.com/37291194/250027546-3fc5ca74-3f58-4bca-92fe-a6bdcda2ad1f.png"> Please use root pseudo-elements for your colors to resolve this:
> 
> ```
> :root {
>   --primary-color: #FF0000;
> }
> 
> .selector1 {
>   color: var(--primary-color);
> }
> 
> .selector2 {
>   color: var(--primary-color);
> }
> ```

Thank you guys. I'll implement suggested changes
